# Builds package and publishes it on npm.
# Triggered on pushes to develop, master and release branches
name: CD

on:
  push:
    branches:
      - master
      - develop
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all branches

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install modules
        run: npm install --no-audit --ignore-scripts

      - name: Build package
        run: npm run build-package

      - name: Run unit tests
        run: CHROME_BIN=`which chrome || which chromium-browser` ENV_BROWSER=Chrome_headless npm run test

      - name: Publish release
        run: npx ci-semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

