# Builds the package and runs all tests.
name: CI

on:
  push:
    branches-ignore:
      - master
      - develop
      - release-*

jobs:
  build:
    runs-on: ubuntu-24.04

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install modules
        run: npm ci --no-audit --ignore-scripts

      - name: Lint
        run: npm run lint

      - name: Build package
        run: npm run build-package

      - name: Run unit tests
        run: |
          export NO_SANDBOX=true
          CHROME_BIN=`which chrome || which chromium-browser` ENV_BROWSER=Chrome_headless npm run test
