# Builds the package and runs all tests.
name: CI

on:
  push:
    branches-ignore:
      - master
      - develop
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install modules
        run: npm install --no-audit

      - name: Lint
        run: npm run lint

      - name: Build package
        run: npm run build-package

      - name: Run unit tests
        run: CHROME_BIN=`which chrome || which chromium-browser` ENV_BROWSER=Chrome_headless npm run test
